### ISSUE TITLE
Color targets by status

### ISSUE THREAD

**Issue by dansondergaard** [Hogfeldt/gwf-graph#2]
This will become easier when gwf 2.0 comes out with more detailed status metadata, but right now you can still color by status by asking the Scheduler what the status of a target is.

**Comment by Hogfeldt** [comment]
Good idea, that could be pretty useful for figuring out which dependency failed down the line.

**Comment by Hogfeldt** [comment]
Resolved in 017dac581af198bee3d372ac5c508420e262446c 

Coloring the targets by it's status can be turned on by the `--status` flag, here is a simple example with and without:
![dependency_graph_no_status gv](https://user-images.githubusercontent.com/17415779/87242986-13557d00-c432-11ea-8cd3-0769265b604d.png)
![dependency_graph_status gv](https://user-images.githubusercontent.com/17415779/87242987-1486aa00-c432-11ea-98b4-c9fd12730ac2.png)
