### ISSUE TITLE
Option to just output the DOT code

### ISSUE THREAD

**Issue by dansondergaard** [Hogfeldt/gwf-graph#4]
Sometimes one may want to modify the output, so an option to just output the DOT code to stdout, instead of rendering the graph, would be nice.

**Comment by Hogfeldt** [comment]
When rendering it also saves the DOT source to a file ("dependency_graph.gv), besides the output file ("dependency_graph.gv.pdf"), so it's possible to modify the graph afterwards. But if one is just interested in the source, there is no reason to spend resources on rendering, so I will add a `--stdout` flag, which will just output the source to stdout, without writing any files.

**Comment by dansondergaard** [comment]
Otherwise just make it a different output format, so you have `cytoscape`, `svg` and `dot`. I think that's simpler for the user :-) Maybe it's time to turn the different output formats into different functions and map the output format string to the appropriate function?

Update: A `--stdout` flag is confusing. For example, what happens if I use `--output-type cytoscape --stdout`?

**Comment by Hogfeldt** [comment]
It's a good point, I'll make it a different output format instead. Would it then be best to always output to a file for consistency? Or maybe always output to stdout? Or would it be okay to switch depending on context?
And I agree the code is starting to look a bit messy. ;)

**Comment by dansondergaard** [comment]
> Would it then be best to always output to a file for consistency? Or maybe always output to stdout? Or would it be okay to switch depending on context?

I think it's fine if the simple stuff like SIF and DOT code is just output to stdout. It's easy to pipe it into other programs or to a file. It depends on context, for example, some day you might want to output a complete web app that draws the graph with D3 or something. That should definitely not go to stdout ;-)

> And I agree the code is starting to look a bit messy. ;)

I think it's great 👍 

Another small thing: I'd rename "cytoscape" to "sif". It's a general format that can be read by other tools than cytoscape, so I think that that makes more sense.

**Comment by Hogfeldt** [comment]
> I think it's fine if the simple stuff like SIF and DOT code is just output to stdout. It's easy to pipe it into other programs or to a file. It depends on context, for example, some day you might want to output a complete web app that draws the graph with D3 or something. That should definitely not go to stdout ;-

Makes sense. Would it be nice to have a `-o, --output` flag so you could choose the file name and location for lets say a `svg` file? And would it then make sense to also use the flag for `dot` format, when the output flag is applied? 

> Another small thing: I'd rename "cytoscape" to "sif". It's a general format that can be read by other tools than cytoscape, so I think that that makes more sense.

Good idea

**Comment by dansondergaard** [comment]
> > I think it's fine if the simple stuff like SIF and DOT code is just output to stdout. It's easy to pipe it into other programs or to a file. It depends on context, for example, some day you might want to output a complete web app that draws the graph with D3 or something. That should definitely not go to stdout ;-
> 
> Makes sense. Would it be nice to have a `-o, --output` flag so you could choose the file name and location for lets say a `svg` file? And would it then make sense to also use the flag for `dot` format, when the output flag is applied?

Yes, that would be nice!

**Comment by Hogfeldt** [comment]
I have made the changes that we have discussed here and added support for all the output formats that graphviz supports. Here is the list:
```
FORMATS = {  # http://www.graphviz.org/doc/info/output.html
    'bmp',
    'canon', 'dot', 'gv', 'xdot', 'xdot1.2', 'xdot1.4',
    'cgimage',
    'cmap',
    'eps',
    'exr',
    'fig',
    'gd', 'gd2',
    'gif',
    'gtk',
    'ico',
    'imap', 'cmapx',
    'imap_np', 'cmapx_np',
    'ismap',
    'jp2',
    'jpg', 'jpeg', 'jpe',
    'json', 'json0', 'dot_json', 'xdot_json',  # Graphviz 2.40
    'pct', 'pict',
    'pdf',
    'pic',
    'plain', 'plain-ext',
    'png',
    'pov',
    'ps',
    'ps2',
    'psd',
    'sgi',
    'svg', 'svgz',
    'tga',
    'tif', 'tiff',
    'tk',
    'vml', 'vmlz',
    'vrml',
    'wbmp',
    'webp',
    'xlib',
    'x11',
}
```
ref: [https://graphviz.readthedocs.io/en/stable/_modules/graphviz/backend.html](url)
